### ISSUE TITLE
Play button doesn't work

### ISSUE THREAD

**Issue by asolera** [emilyskidsister/hacklily#17]
The "Play" button isn't working.

It displays CORS error in console log:

```
Access to fetch at 'https://www.hacklily.org/hackmidi/samples/timidity.cfg' from origin 'https://hacklily.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by emilyskidsister** [comment]
Do you see this when running Hacklily locally or on hacklily.org? Are you able to reproduce this in Incognito/with adblockers disabled?

**Comment by asolera** [comment]
> Do you see this when running Hacklily locally or on hacklily.org? Are you able to reproduce this in Incognito/with adblockers disabled?

I'm trying to reproduce directly on https://hacklily.org/ page, and it didn't work in incognito mode without adblockers.

**Comment by Paamayim-Nekudotayim** [comment]
The Play button is not working if the user visits https://hacklily.org instead of https://www.hacklily.org.

The evil CORS is blocking requests to `www.hacklily.org` from `hacklily.org`.

**Comment by emilyskidsister** [comment]
Great catch!
