### ISSUE TITLE
MusicXML import

### ISSUE THREAD

**Issue by PaulMorris** [emilyskidsister/hacklily#25]
The ability to import MusicXML files (using LilyPond's musicxml2ly) would be a nice feature.  I checked the source code and commit history, and it looks like some work has been done on this[1] but I did not find a way to do an import in the UI.  So I'm curious about the current status and what remains to be done for this.

[1] MusicXML commits: https://github.com/jnetterf/hacklily/commit/9eb5821d0f80de2a8d319dd568897c6502fb274e https://github.com/jnetterf/hacklily/commit/cfee68c086db2196dd3fc6493a6715b8046472d2

**Comment by PaulMorris** [comment]
After looking closer at the source code, I see that musicxml2ly import can be accessed at `https://hacklily.org/musicxml2ly`.  I tried a few files but each time I got this error: `Could not render file: Crashed during render: Canary died.`

**Comment by emilyskidsister** [comment]
Thank you for reporting, this should be resolved now.
