### ISSUE TITLE
"Something went wrong. Could not log you in." when open/save to github.

### ISSUE THREAD

**Issue by djbclark** [emilyskidsister/hacklily#28]
Getting a pop-up with "Something went wrong. Could not log you in." when open/save to github. 

The initial repo creation of the public sheet-music repo did work. 

Tried from Chrome and Firefox, tried disabling ad blockers, tried incognito/private mode, no dice. I just have normal auth set up on github, no two-factor or anything. 

I also tried making a brand new github account - hacklillytest - same issue.

**Comment by djbclark** [comment]
The workaround in the closed #14 worked, however IMHO this shouldn't be closed until either the software is updated to deal with github's change or this is doc'ed in README.md, as this is a problem that all new users are going to hit, and even people who try to be conscientious may not think to look for workarounds in closed issues.

**Comment by emilyskidsister** [comment]
Thank you for reporting, this should be resolved now.
