### ISSUE TITLE
Music may be played at wrong speed (too fast)

### ISSUE THREAD

**Issue by Paamayim-Nekudotayim** [emilyskidsister/hacklily#52]
Hello!

There is an issue with the Play button. On some computer, the sound you hear is pitched almost a semitone too high, because it is played  too fast.

This is due to an erroneous AudioContext instantiation in Hackmidi module. Audio Context is created using system default sampling rate, which can be 48000 Hz, while MIDI notes are converted at 44100 Hz.

To fix the issue you can now pass the same sampling rate as the audio conversion as an argument as described here: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext#example

**Comment by emilyskidsister** [comment]
Thank you for the report 🙂
